services:
  openstock:
    build:
      context: .
      args:
        NEXT_PUBLIC_FINNHUB_API_KEY: ${NEXT_PUBLIC_FINNHUB_API_KEY}
      extra_hosts:
        - "mongodb:host-gateway"
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://root:example@mongodb:27017/openstock?authSource=admin
      NEXT_PUBLIC_SOURCE_CODE_URL: https://github.com/chintasamsonhruday/stock_tracker
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
